threads = 14
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15 Safari/604.1"
follow_redirects = true
max_redirects = 10
insecure = false
modules = ["all"]
timeout = 31
payload_limit = 50
exploitation_level = 35
crawl_depth = 4
max_urls = 100
jobs = 3

[headers]
